// Emits csharp/src/Cairn.Core/Shared/SharedData.g.cs from the TypeScript sources of truth, so large constant
// tables (code-language ids, theme palettes, starter notes) are never retyped by hand.
//
//   npx vite-node -c vitest.config.ts csharp/scripts/generate-shared-data.ts
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CODE_LANGUAGES, DEFAULT_ENABLED_CODE_LANGUAGES } from "../../shared/codeLanguages";
import { DEFAULT_DARK_COLORS, DEFAULT_LIGHT_COLORS, THEME_COLOR_VAR_NAMES } from "../../shared/themeColors";
import { STARTER_NOTES } from "../../shared/starterContent";

const here = path.dirname(fileURLToPath(import.meta.url));
const str = (s: string) => JSON.stringify(s);
const list = (items: string[]) => items.map(str).join(", ");
const dict = (d: Record<string, string>, names: string[]) =>
  names.map((n) => `        [${str(n)}] = ${str(d[n])},`).join("\n");

const out = `// <auto-generated>
// Generated by csharp/scripts/generate-shared-data.ts from the TypeScript sources in shared/. Do not edit by hand.
// </auto-generated>
namespace Cairn.Core.Shared;

public static partial class SharedData
{
    public static readonly string[] CodeLanguageIds = { ${list(CODE_LANGUAGES.map((l) => l.id))} };

    public static readonly string[] DefaultEnabledCodeLanguages = { ${list(DEFAULT_ENABLED_CODE_LANGUAGES)} };

    public static readonly string[] ThemeColorVarNames = { ${list(THEME_COLOR_VAR_NAMES)} };

    public static readonly IReadOnlyDictionary<string, string> DefaultDarkColors = new Dictionary<string, string>
    {
${dict(DEFAULT_DARK_COLORS, THEME_COLOR_VAR_NAMES)}
    };

    public static readonly IReadOnlyDictionary<string, string> DefaultLightColors = new Dictionary<string, string>
    {
${dict(DEFAULT_LIGHT_COLORS, THEME_COLOR_VAR_NAMES)}
    };

    public static readonly (string FileName, string Content)[] StarterNotes =
    {
${STARTER_NOTES.map((n) => `        (${str(n.fileName)}, ${str(n.content)}),`).join("\n")}
    };
}
`;

const target = path.join(here, "..", "src", "Cairn.Core", "Shared", "SharedData.g.cs");
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out, "utf-8");
console.log("wrote", target);
