// Generated from the language grammars bundled with highlight.js (see
// src/editor/codeHighlight.ts) — id is the highlight.js grammar file name,
// used both to look up/lazily import the grammar and as the persisted
// settings value. Brainfuck is intentionally excluded.
export interface CodeLanguage {
  id: string;
  name: string;
  aliases: string[];
}

export const CODE_LANGUAGES: CodeLanguage[] = [
  { id: "properties", name: ".properties", aliases: [] },
  { id: "1c", name: "1C:Enterprise", aliases: [] },
  { id: "actionscript", name: "ActionScript", aliases: ["as"] },
  { id: "ada", name: "Ada", aliases: [] },
  { id: "angelscript", name: "AngelScript", aliases: ["asc"] },
  { id: "accesslog", name: "Apache Access Log", aliases: [] },
  { id: "apache", name: "Apache config", aliases: ["apacheconf"] },
  { id: "applescript", name: "AppleScript", aliases: ["osascript"] },
  { id: "arcade", name: "ArcGIS Arcade", aliases: [] },
  { id: "arduino", name: "Arduino", aliases: ["ino"] },
  { id: "armasm", name: "ARM Assembly", aliases: ["arm"] },
  { id: "asciidoc", name: "AsciiDoc", aliases: ["adoc"] },
  { id: "aspectj", name: "AspectJ", aliases: [] },
  { id: "abnf", name: "Augmented Backus-Naur Form", aliases: [] },
  { id: "autohotkey", name: "AutoHotkey", aliases: ["ahk"] },
  { id: "autoit", name: "AutoIt", aliases: [] },
  { id: "avrasm", name: "AVR Assembly", aliases: [] },
  { id: "awk", name: "Awk", aliases: [] },
  { id: "bnf", name: "Backus–Naur Form", aliases: [] },
  { id: "bash", name: "Bash", aliases: ["sh","zsh"] },
  { id: "basic", name: "BASIC", aliases: [] },
  { id: "dos", name: "Batch file (DOS)", aliases: ["bat","batch","cmd"] },
  { id: "c", name: "C", aliases: ["h"] },
  { id: "cal", name: "C/AL", aliases: [] },
  { id: "csharp", name: "C#", aliases: ["cs","c#"] },
  { id: "cpp", name: "C++", aliases: ["cc","c++","h++","hpp","hh","hxx","cxx"] },
  { id: "cos", name: "Caché Object Script", aliases: ["cls"] },
  { id: "capnproto", name: "Cap’n Proto", aliases: ["capnp"] },
  { id: "ceylon", name: "Ceylon", aliases: [] },
  { id: "clean", name: "Clean", aliases: ["icl","dcl"] },
  { id: "clojure", name: "Clojure", aliases: ["clj","edn"] },
  { id: "clojure-repl", name: "Clojure REPL", aliases: [] },
  { id: "cmake", name: "CMake", aliases: ["cmake.in"] },
  { id: "coffeescript", name: "CoffeeScript", aliases: ["coffee","cson","iced"] },
  { id: "coq", name: "Coq", aliases: [] },
  { id: "crmsh", name: "crmsh", aliases: ["crm","pcmk"] },
  { id: "crystal", name: "Crystal", aliases: ["cr"] },
  { id: "csp", name: "CSP", aliases: [] },
  { id: "css", name: "CSS", aliases: [] },
  { id: "d", name: "D", aliases: [] },
  { id: "dart", name: "Dart", aliases: [] },
  { id: "delphi", name: "Delphi", aliases: ["dpr","dfm","pas","pascal"] },
  { id: "dts", name: "Device Tree", aliases: [] },
  { id: "diff", name: "Diff", aliases: ["patch"] },
  { id: "django", name: "Django", aliases: ["jinja"] },
  { id: "dns", name: "DNS Zone", aliases: ["bind","zone"] },
  { id: "dockerfile", name: "Dockerfile", aliases: ["docker"] },
  { id: "dsconfig", name: "dsconfig", aliases: [] },
  { id: "dust", name: "Dust", aliases: ["dst"] },
  { id: "elixir", name: "Elixir", aliases: ["ex","exs"] },
  { id: "elm", name: "Elm", aliases: [] },
  { id: "erb", name: "ERB", aliases: [] },
  { id: "erlang", name: "Erlang", aliases: ["erl"] },
  { id: "erlang-repl", name: "Erlang REPL", aliases: [] },
  { id: "excel", name: "Excel formulae", aliases: ["xlsx","xls"] },
  { id: "ebnf", name: "Extended Backus-Naur Form", aliases: [] },
  { id: "fsharp", name: "F#", aliases: ["fs","f#"] },
  { id: "fix", name: "FIX", aliases: [] },
  { id: "flix", name: "Flix", aliases: [] },
  { id: "fortran", name: "Fortran", aliases: ["f90","f95"] },
  { id: "freedesktop", name: "FreeDesktop config", aliases: ["desktop","systemd"] },
  { id: "gcode", name: "G-code (ISO 6983)", aliases: ["nc"] },
  { id: "gams", name: "GAMS", aliases: ["gms"] },
  { id: "gauss", name: "GAUSS", aliases: ["gss"] },
  { id: "gherkin", name: "Gherkin", aliases: ["feature"] },
  { id: "glsl", name: "GLSL", aliases: [] },
  { id: "gml", name: "GML", aliases: [] },
  { id: "go", name: "Go", aliases: ["golang"] },
  { id: "golo", name: "Golo", aliases: [] },
  { id: "gradle", name: "Gradle", aliases: [] },
  { id: "graphql", name: "GraphQL", aliases: ["gql"] },
  { id: "groovy", name: "Groovy", aliases: [] },
  { id: "haml", name: "HAML", aliases: [] },
  { id: "handlebars", name: "Handlebars", aliases: ["hbs","html.hbs","html.handlebars","htmlbars"] },
  { id: "haskell", name: "Haskell", aliases: ["hs"] },
  { id: "haxe", name: "Haxe", aliases: ["hx"] },
  { id: "hsp", name: "HSP", aliases: [] },
  { id: "xml", name: "HTML, XML", aliases: ["html","xhtml","rss","atom","xjb","xsd","xsl","plist","wsf","svg"] },
  { id: "http", name: "HTTP", aliases: ["https"] },
  { id: "hy", name: "Hy", aliases: ["hylang"] },
  { id: "inform7", name: "Inform 7", aliases: ["i7"] },
  { id: "x86asm", name: "Intel x86 Assembly", aliases: [] },
  { id: "irpf90", name: "IRPF90", aliases: [] },
  { id: "isbl", name: "ISBL", aliases: [] },
  { id: "java", name: "Java", aliases: ["jsp"] },
  { id: "javascript", name: "JavaScript", aliases: ["js","jsx","mjs","cjs"] },
  { id: "jboss-cli", name: "JBoss CLI", aliases: ["wildfly-cli"] },
  { id: "json", name: "JSON", aliases: ["jsonc","json5"] },
  { id: "julia", name: "Julia", aliases: [] },
  { id: "julia-repl", name: "Julia REPL", aliases: ["jldoctest"] },
  { id: "kotlin", name: "Kotlin", aliases: ["kt","kts","ktm","ktx"] },
  { id: "lasso", name: "Lasso", aliases: ["ls","lassoscript"] },
  { id: "latex", name: "LaTeX", aliases: ["tex"] },
  { id: "ldif", name: "LDIF", aliases: [] },
  { id: "leaf", name: "Leaf", aliases: [] },
  { id: "less", name: "Less", aliases: [] },
  { id: "lisp", name: "Lisp", aliases: [] },
  { id: "livecodeserver", name: "LiveCode", aliases: [] },
  { id: "livescript", name: "LiveScript", aliases: ["ls"] },
  { id: "llvm", name: "LLVM IR", aliases: [] },
  { id: "lsl", name: "LSL (Linden Scripting Language)", aliases: [] },
  { id: "lua", name: "Lua", aliases: ["pluto"] },
  { id: "makefile", name: "Makefile", aliases: ["mk","mak","make"] },
  { id: "markdown", name: "Markdown", aliases: ["md","mkdown","mkd"] },
  { id: "mathematica", name: "Mathematica", aliases: ["mma","wl"] },
  { id: "matlab", name: "Matlab", aliases: [] },
  { id: "maxima", name: "Maxima", aliases: [] },
  { id: "mel", name: "MEL", aliases: [] },
  { id: "mercury", name: "Mercury", aliases: ["m","moo"] },
  { id: "routeros", name: "MikroTik RouterOS script", aliases: ["mikrotik"] },
  { id: "mipsasm", name: "MIPS Assembly", aliases: ["mips"] },
  { id: "mizar", name: "Mizar", aliases: [] },
  { id: "mojolicious", name: "Mojolicious", aliases: [] },
  { id: "monkey", name: "Monkey", aliases: [] },
  { id: "moonscript", name: "MoonScript", aliases: ["moon"] },
  { id: "n1ql", name: "N1QL", aliases: [] },
  { id: "nestedtext", name: "Nested Text", aliases: ["nt"] },
  { id: "nginx", name: "Nginx config", aliases: ["nginxconf"] },
  { id: "nim", name: "Nim", aliases: [] },
  { id: "nix", name: "Nix", aliases: ["nixos"] },
  { id: "node-repl", name: "Node REPL", aliases: [] },
  { id: "nsis", name: "NSIS", aliases: [] },
  { id: "objectivec", name: "Objective-C", aliases: ["mm","objc","obj-c","obj-c++","objective-c++"] },
  { id: "ocaml", name: "OCaml", aliases: ["ml"] },
  { id: "openscad", name: "OpenSCAD", aliases: ["scad"] },
  { id: "ruleslanguage", name: "Oracle Rules Language", aliases: [] },
  { id: "oxygene", name: "Oxygene", aliases: [] },
  { id: "pf", name: "Packet Filter config", aliases: ["pf.conf"] },
  { id: "parser3", name: "Parser3", aliases: [] },
  { id: "perl", name: "Perl", aliases: ["pl","pm"] },
  { id: "php", name: "php", aliases: [] },
  { id: "php-template", name: "PHP template", aliases: [] },
  { id: "plaintext", name: "Plain text", aliases: ["text","txt"] },
  { id: "pony", name: "Pony", aliases: [] },
  { id: "pgsql", name: "PostgreSQL", aliases: ["postgres","postgresql"] },
  { id: "powershell", name: "PowerShell", aliases: ["pwsh","ps","ps1"] },
  { id: "processing", name: "Processing", aliases: ["pde"] },
  { id: "prolog", name: "Prolog", aliases: [] },
  { id: "protobuf", name: "Protocol Buffers", aliases: ["proto"] },
  { id: "puppet", name: "Puppet", aliases: ["pp"] },
  { id: "purebasic", name: "PureBASIC", aliases: ["pb","pbi"] },
  { id: "python", name: "Python", aliases: ["py","gyp","ipython"] },
  { id: "profile", name: "Python profiler", aliases: [] },
  { id: "python-repl", name: "python-repl", aliases: ["pycon"] },
  { id: "q", name: "Q", aliases: ["k","kdb"] },
  { id: "qml", name: "QML", aliases: ["qt"] },
  { id: "r", name: "R", aliases: [] },
  { id: "reasonml", name: "ReasonML", aliases: ["re"] },
  { id: "rib", name: "RenderMan RIB", aliases: [] },
  { id: "rsl", name: "RenderMan RSL", aliases: [] },
  { id: "roboconf", name: "Roboconf", aliases: ["graph","instances"] },
  { id: "ruby", name: "Ruby", aliases: ["rb","gemspec","podspec","thor","irb"] },
  { id: "rust", name: "Rust", aliases: ["rs"] },
  { id: "sas", name: "SAS", aliases: [] },
  { id: "scala", name: "Scala", aliases: [] },
  { id: "scheme", name: "Scheme", aliases: ["scm"] },
  { id: "scilab", name: "Scilab", aliases: ["sci"] },
  { id: "scss", name: "SCSS", aliases: [] },
  { id: "shell", name: "Shell Session", aliases: ["console","shellsession"] },
  { id: "smali", name: "Smali", aliases: [] },
  { id: "smalltalk", name: "Smalltalk", aliases: ["st"] },
  { id: "sml", name: "SML (Standard ML)", aliases: ["ml"] },
  { id: "sqf", name: "SQF", aliases: [] },
  { id: "sql", name: "SQL", aliases: [] },
  { id: "stan", name: "Stan", aliases: ["stanfuncs"] },
  { id: "stata", name: "Stata", aliases: ["do","ado"] },
  { id: "step21", name: "STEP Part 21", aliases: ["p21","step","stp"] },
  { id: "stylus", name: "Stylus", aliases: ["styl"] },
  { id: "subunit", name: "SubUnit", aliases: [] },
  { id: "swift", name: "Swift", aliases: [] },
  { id: "taggerscript", name: "Tagger Script", aliases: [] },
  { id: "tcl", name: "Tcl", aliases: ["tk"] },
  { id: "tap", name: "Test Anything Protocol", aliases: [] },
  { id: "thrift", name: "Thrift", aliases: [] },
  { id: "ini", name: "TOML, also INI", aliases: ["toml"] },
  { id: "tp", name: "TP", aliases: [] },
  { id: "twig", name: "Twig", aliases: ["craftcms"] },
  { id: "typescript", name: "TypeScript", aliases: ["ts","tsx","mts","cts"] },
  { id: "vala", name: "Vala", aliases: [] },
  { id: "vbscript", name: "VBScript", aliases: ["vbs"] },
  { id: "vbscript-html", name: "VBScript in HTML", aliases: [] },
  { id: "verilog", name: "Verilog", aliases: ["v","sv","svh"] },
  { id: "vhdl", name: "VHDL", aliases: [] },
  { id: "vim", name: "Vim Script", aliases: [] },
  { id: "vbnet", name: "Visual Basic .NET", aliases: ["vb"] },
  { id: "wasm", name: "WebAssembly", aliases: [] },
  { id: "wren", name: "Wren", aliases: [] },
  { id: "axapta", name: "X++", aliases: ["x++"] },
  { id: "xl", name: "XL", aliases: ["tao"] },
  { id: "xquery", name: "XQuery", aliases: ["xpath","xq","xqm"] },
  { id: "yaml", name: "YAML", aliases: ["yml"] },
  { id: "zephir", name: "Zephir", aliases: ["zep"] },
];

/** Maps every id and alias (e.g. "js", "html") to its canonical CODE_LANGUAGES id. */
export const CODE_LANGUAGE_ALIASES: Record<string, string> = (() => {
  const map: Record<string, string> = {};
  for (const lang of CODE_LANGUAGES) {
    map[lang.id] = lang.id;
    for (const alias of lang.aliases) map[alias] = lang.id;
  }
  return map;
})();

export const DEFAULT_ENABLED_CODE_LANGUAGES: string[] = [
  "csharp",
  "applescript",
  "bash",
  "c",
  "cpp",
  "java",
  "javascript",
  "typescript",
  "xml",
  "css",
  "gherkin",
  "json",
  "kotlin",
  "markdown",
];
