// <auto-generated>
// Generated by csharp/scripts/generate-shared-data.ts from the TypeScript sources in shared/. Do not edit by hand.
// </auto-generated>
namespace Cairn.Core.Shared;

public static partial class SharedData
{
    public static readonly string[] CodeLanguageIds = { "properties", "1c", "actionscript", "ada", "angelscript", "accesslog", "apache", "applescript", "arcade", "arduino", "armasm", "asciidoc", "aspectj", "abnf", "autohotkey", "autoit", "avrasm", "awk", "bnf", "bash", "basic", "dos", "c", "cal", "csharp", "cpp", "cos", "capnproto", "ceylon", "clean", "clojure", "clojure-repl", "cmake", "coffeescript", "coq", "crmsh", "crystal", "csp", "css", "d", "dart", "delphi", "dts", "diff", "django", "dns", "dockerfile", "dsconfig", "dust", "elixir", "elm", "erb", "erlang", "erlang-repl", "excel", "ebnf", "fsharp", "fix", "flix", "fortran", "freedesktop", "gcode", "gams", "gauss", "gherkin", "glsl", "gml", "go", "golo", "gradle", "graphql", "groovy", "haml", "handlebars", "haskell", "haxe", "hsp", "xml", "http", "hy", "inform7", "x86asm", "irpf90", "isbl", "java", "javascript", "jboss-cli", "json", "julia", "julia-repl", "kotlin", "lasso", "latex", "ldif", "leaf", "less", "lisp", "livecodeserver", "livescript", "llvm", "lsl", "lua", "makefile", "markdown", "mathematica", "matlab", "maxima", "mel", "mercury", "routeros", "mipsasm", "mizar", "mojolicious", "monkey", "moonscript", "n1ql", "nestedtext", "nginx", "nim", "nix", "node-repl", "nsis", "objectivec", "ocaml", "openscad", "ruleslanguage", "oxygene", "pf", "parser3", "perl", "php", "php-template", "plaintext", "pony", "pgsql", "powershell", "processing", "prolog", "protobuf", "puppet", "purebasic", "python", "profile", "python-repl", "q", "qml", "r", "reasonml", "rib", "rsl", "roboconf", "ruby", "rust", "sas", "scala", "scheme", "scilab", "scss", "shell", "smali", "smalltalk", "sml", "sqf", "sql", "stan", "stata", "step21", "stylus", "subunit", "swift", "taggerscript", "tcl", "tap", "thrift", "ini", "tp", "twig", "typescript", "vala", "vbscript", "vbscript-html", "verilog", "vhdl", "vim", "vbnet", "wasm", "wren", "axapta", "xl", "xquery", "yaml", "zephir" };

    public static readonly string[] DefaultEnabledCodeLanguages = { "csharp", "applescript", "bash", "c", "cpp", "java", "javascript", "typescript", "xml", "css", "gherkin", "json", "kotlin", "markdown" };

    public static readonly string[] ThemeColorVarNames = { "bg-base", "bg-recessed", "bg-sidebar", "bg-tabbar", "bg-surface", "bg-control", "bg-control-hover", "bg-selected", "bg-tag", "bg-wikilink", "bg-wikilink-orphan", "bg-highlight", "scrollbar-thumb", "scrollbar-thumb-hover", "border-divider", "border-control", "text-primary", "text-secondary", "text-tertiary", "text-muted", "text-faint", "text-faintest", "text-quote", "text-label", "text-onbutton", "text-strong", "text-disabled", "accent-blue", "accent-purple", "accent-green", "accent-red", "accent-red-soft", "accent-violet", "shadow-menu", "overlay-bg" };

    public static readonly IReadOnlyDictionary<string, string> DefaultDarkColors = new Dictionary<string, string>
    {
        ["bg-base"] = "#1e1f24",
        ["bg-recessed"] = "#1a1b20",
        ["bg-sidebar"] = "#23242b",
        ["bg-tabbar"] = "#202127",
        ["bg-surface"] = "#2a2c38",
        ["bg-control"] = "#35374a",
        ["bg-control-hover"] = "#454868",
        ["bg-selected"] = "#3a3d55",
        ["bg-tag"] = "#3a2d4a",
        ["bg-wikilink"] = "#22304a",
        ["bg-wikilink-orphan"] = "#3a2323",
        ["bg-highlight"] = "#6b5a1f",
        ["scrollbar-thumb"] = "#3a3d55",
        ["scrollbar-thumb-hover"] = "#4a4c68",
        ["border-divider"] = "#33343d",
        ["border-control"] = "#4a4c63",
        ["text-primary"] = "#e6e6e6",
        ["text-secondary"] = "#999",
        ["text-tertiary"] = "#ccc",
        ["text-muted"] = "#888",
        ["text-faint"] = "#777",
        ["text-faintest"] = "#666",
        ["text-quote"] = "#aaa",
        ["text-label"] = "#b6b6c0",
        ["text-onbutton"] = "#ddd",
        ["text-strong"] = "#fff",
        ["text-disabled"] = "#4a4c56",
        ["accent-blue"] = "#6c9bd1",
        ["accent-purple"] = "#a97bd1",
        ["accent-green"] = "#5a9b6e",
        ["accent-red"] = "#e07a7a",
        ["accent-red-soft"] = "#d17b7b",
        ["accent-violet"] = "#7a7dc9",
        ["shadow-menu"] = "rgba(0, 0, 0, 0.4)",
        ["overlay-bg"] = "rgba(0, 0, 0, 0.5)",
    };

    public static readonly IReadOnlyDictionary<string, string> DefaultLightColors = new Dictionary<string, string>
    {
        ["bg-base"] = "#ffffff",
        ["bg-recessed"] = "#eef0f3",
        ["bg-sidebar"] = "#f7f8fa",
        ["bg-tabbar"] = "#eef0f3",
        ["bg-surface"] = "#f1f2f5",
        ["bg-control"] = "#eceef2",
        ["bg-control-hover"] = "#dfe2e8",
        ["bg-selected"] = "#dbe7fb",
        ["bg-tag"] = "#f1e9fb",
        ["bg-wikilink"] = "#e3edfb",
        ["bg-wikilink-orphan"] = "#fbe4e4",
        ["bg-highlight"] = "#fff3a3",
        ["scrollbar-thumb"] = "#c7cad1",
        ["scrollbar-thumb-hover"] = "#b3b7c1",
        ["border-divider"] = "#e1e3e8",
        ["border-control"] = "#8b909c",
        ["text-primary"] = "#1f2328",
        ["text-secondary"] = "#57606a",
        ["text-tertiary"] = "#4d525c",
        ["text-muted"] = "#6e7781",
        ["text-faint"] = "#7d8590",
        ["text-faintest"] = "#7d8590",
        ["text-quote"] = "#57606a",
        ["text-label"] = "#57606a",
        ["text-onbutton"] = "#24292f",
        ["text-strong"] = "#14171a",
        ["text-disabled"] = "#b6bac2",
        ["accent-blue"] = "#2b6cb0",
        ["accent-purple"] = "#7a4fc2",
        ["accent-green"] = "#2f8552",
        ["accent-red"] = "#c53030",
        ["accent-red-soft"] = "#ae2e24",
        ["accent-violet"] = "#6a63c9",
        ["shadow-menu"] = "rgba(20, 20, 30, 0.15)",
        ["overlay-bg"] = "rgba(15, 15, 20, 0.35)",
    };

    public static readonly (string FileName, string Content)[] StarterNotes =
    {
        ("Welcome.md", "---\ntags: [example]\n---\n# Welcome to Cairn\n\nThis is a folder of plain markdown files — nothing here is stored in a\ndatabase, so you can edit these notes in Cairn or in any other text editor\nand both will stay in sync.\n\nTwo ideas make this more than a folder of files:\n\n- Type `[[` to link to another note, e.g. [[Example Note]]. Links work\n  both ways — open Example Note and you'll see this note listed as a\n  backlink.\n- Add a `#tag` anywhere in a note (like the `#example` tag on this one)\n  to group it with every other note carrying that tag, without linking to\n  them individually.\n\nOpen the graph view (◇ in the left rail) to see how it all connects.\n\nDelete these notes whenever you're ready — they're just here to show the\nshape of things.\n"),
        ("Example Note.md", "---\ntags: [example]\n---\n# Example Note\n\nLinked back to [[Welcome]] — click the link, or check its Links panel, to\nsee this note listed as a backlink.\n\nThis note also shares the `#example` tag with Welcome, which is why\nthey're connected in the graph even without linking directly.\n"),
    };
}
